---
# vars file for install-monit-tools
url_repo_helm: prometheus-community https://prometheus-community.github.io/helm-charts
deploy_prometheus: "meu-querido-prometheus prometheus-community/kube-prometheus-stack"
