BOX_IMAGE = "generic/ubuntu2004"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
    config.vm.define "ansible-01" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.hostname = "ansible-01"
    end

    (1..NODE_COUNT).each do |i|
      config.vm.define "web#{i}" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.hostname = "web#{i}"
      end
     end

  config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update && apt upgrade -y
    apt install vim git htop -y
  SHELL

end
