- hosts: all
  become: yes
  user: vagrant
  gather_facts: no
  pre_tasks:
  - name: 'Atualizando o repo'
    raw: 'apt update'
  
  - name: 'Instalando o Python'
    raw: 'apt install -y python'

  - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
    shell: |
      swapoff -a

  - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'

  roles:
    - { role: install-k8s, tags: ["install_k8s_role"] }

- hosts: k8s-master
  become: yes
  user: vagrant
  roles:
  - { role: create-cluster, tags: ["create_cluster_role"] }

- hosts: k8s-workers
  become: yes
  user: vagrant
  roles:
  - { role: join-workers, tags: ["join_workers_roles"] }

- hosts: k8s-master
  become: yes
  user: vagrant
  roles:
  - { role: install-helm, tags: ["install_helm3_role"] }

- hosts: k8s-master
  become: yes
  user: vagrant
  roles:
  - { role: install-monit-tools, tags: ["install_monit_tools_role"] }

